name: Context Variables demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "This workflow is triggered by ${{ github.actor }}
          echo "the repository name is ${{ github.repository }}
      - name: Print all variables under github
        run: "${{toJson(github)}}"
